In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7032, 5690, 8640, 7992],
 [7032, 5690, 8640, 1579],
 [7032, 372, 8640, 7271],
 [2163, 590, 5663, 8280, 3503],
 [2163, 590, 5663, 8280, 2590],
 [5148, 7032, 3533, 8640, 5597],
 [4633, 7308, 6868, 8280]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7032 5690 8640 7992]
 [   0    0    0    0 7032 5690 8640 1579]
 [   0    0    0    0 7032  372 8640 7271]
 [   0    0    0 2163  590 5663 8280 3503]
 [   0    0    0 2163  590 5663 8280 2590]
 [   0    0    0 5148 7032 3533 8640 5597]
 [   0    0    0    0 4633 7308 6868 8280]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile(optimizer='adam', loss='mse')

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step


array([[[ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.00022627,  0.04917793, -0.0140875 , -0.01343317,
         -0.00416633,  0.02186799,  0.02008554, -0.03043377,
          0.00253335,  0.01479122],
        [-0.02188843,  0.01596392,  0.01415796,  0.04133776,
          0.01637575,  0.01263095, -0.03905321, -0.03754703,
         -0.02204812, -0.04159371],
        [ 0.04098168, -0.00079953,  0.04225358, -0.0

In [14]:
input_data = np.expand_dims(embedded_docs[0], axis=0) 

In [15]:
model.predict(input_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([[[ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.0368345 , -0.03553319, -0.02622083,  0.0012732 ,
          0.01477733,  0.02231291,  0.00135132,  0.02037015,
         -0.04095364,  0.01340872],
        [ 0.00022627,  0.04917793, -0.0140875 , -0.01343317,
         -0.00416633,  0.02186799,  0.02008554, -0.03043377,
          0.00253335,  0.01479122],
        [-0.02188843,  0.01596392,  0.01415796,  0.04133776,
          0.01637575,  0.01263095, -0.03905321, -0.03754703,
         -0.02204812, -0.04159371],
        [ 0.04098168, -0.00079953,  0.04225358, -0.0